### ISSUE TITLE
WebInject can't add arbitrary cookies to requests

### ISSUE THREAD

**Issue by kuchytgj** [sni/Webinject#16]
We have a web application from an outside developer that uses javascript on a form submission event to set a cookie in the browser. This cookie is critical to authentication (i.e. if the cookie isn't present it rejects a POST with creds).

We are using Webinject to test authentication through the web application to ensure users are able to login.

While this quirk is in my opinion a failing of the application it would be nice for Webinject to be flexible enough to support the ability to add arbitrary cookies to a test case.

I have the following patch to do this...

<pre>diff --git a/lib/Webinject.pm b/lib/Webinject.pm
index ddb43af..6dc801a 100644
--- a/lib/Webinject.pm
+++ b/lib/Webinject.pm
@@ -904,7 +904,18 @@ sub _http_defaults {
     my $request   = shift;
     my $useragent = shift;
     my $case      = shift;
-
+
+       if($case->{'addcookie'}) {
+               my $cookie_jar = $useragent->cookie_jar();
+               # add cookies to the cookie jar
+               # can add multiple cookies with a pipe delimiter
+               for my $addcookie (split /\|/mx, $case->{'addcookie'}) {
+                               my ($ck_version, $ck_key, $ck_val, $ck_path, $ck_domain, $ck_port, $ck_path_spec, $ck_secure, $ck_maxage, $ck_discard) = split(/,/, $addcookie);
+                               $cookie_jar->set_cookie( $ck_version, $ck_key, $ck_val, $ck_path, $ck_domain, $ck_port, $ck_path_spec, $ck_secure, $ck_maxage, $ck_discard);
+               }
+               $cookie_jar->save();
+               $cookie_jar->add_cookie_header($request);
+       }
     # add an additional HTTP Header if specified
     if($case->{'addheader'}) {
         # can add multiple headers with a pipe delimiter
</pre>
Which supports a new attribute in test cases with the following format
<code>addcookie="0,PS_DEVICEFEATURES,width:1680,/,host.domain.tld,0,1,1,86400,0"</code>

Which is basically the exact arguments to the cookie jar set_cookie method.

Would this functionality be acceptable as a feature addition?

If so, is this approach acceptable, if not suggestions for how to change things to make it acceptable?

I figured I would work out the details here before submitting a pull request, sorry if that's not preferable!

**Comment by sni** [comment]
Sounds ok for me. Could you please add a few lines of POD documentation on how to use this? I know the test cases are not explained very well in POD for now, but at least new things should be documented.

**Comment by kuchytgj** [comment]
Submitted pull request #17 

Marking as closed.
