### ISSUE TITLE
New method : application/json;charset=utf-8

### ISSUE THREAD

**Issue by Tetsumaki** [sni/Webinject#19]
Hello,

The post method : **application/json;charset=utf-8** will be supported in the future ?

**I have this error when query a mapservice :**
ERROR: Bad Form Encoding Type, I only accept "application/x-www-form-urlencoded", "multipart/form-data", "text/xml", "application/soap+xml"

Another thing, I pray for NTLM authentication managed natively in your code.

**Comment by raheelh** [comment]
I just added a pull request for application/json support.

**Comment by sni** [comment]
Thanks, i just merged it

**Comment by raheelh** [comment]
Thanks, @sni !

**Comment by Tetsumaki** [comment]
Thanks @raheelh !
