### ISSUE TITLE
addheader change __ into --

### ISSUE THREAD

**Issue by dream91** [sni/Webinject#25]
I use addheader in webinject test:

addheader="__RequestVerificationToken: {PARSEDRESULT}"

In request debug header (in http.log) I see: --RequestVerificationToken: TOKEN
I think it should be __RequestVerificationToken insted of --RequestVerificationToken

So I can not complete the request because of wrong header.

Am I doing something wrong?

**Comment by jimbobmcgee** [comment]
A brief look at the code suggests that `addheader` is implemented using the `HTTP::Headers` module, which is external to Webinject.  The `-` to `_` conversion appears to be a 'convenience' method in that library.

That module's documentation suggests that you can prefix your header name with `:` to prevent this conversion, and I can't see anything in Webinject's handling that would preclude that, so try:

    addheader=":__RequestVerificationToken: {PARSEDRESULT}"

http://search.cpan.org/~oalders/HTTP-Message-6.13/lib/HTTP/Headers.pm#NON-CANONICALIZED_FIELD_NAMES
