### ISSUE TITLE
execution out side webinject directory

### ISSUE THREAD

**Issue by chawfr** [sni/Webinject#8]
Webinject wors fine when executed from its directory.
When ran from outside the directory the script shows the usage.

[root@rcifrlv12 ~]# /opt/logi/webinject-1.8.6/webinject.pl -c config.xml AMP_Crg.xml
ERROR: Failed to open config.xml file: Aucun fichier ou r▒pertoire de ce type
    Usage:
      /opt/logi/webinject-1.8.6/webinject.pl
                [-c|--config config_file]
                [-o|--output output_location]
                [-n|--no-output]
                [-t|--timeout]
                [-r|--report-type]
                [-s key=value]
                [testcase_file [XPath]]
      /opt/logi/webinject-1.8.6/webinject.pl --version|-v

The version 1.4.1 works fine in both situations.

Thank you 
Best Regards

**Comment by jimbobmcgee** [comment]
Hi @chawfr 

At some point after v1.4.1 was released, the code that looks for `config.xml` was changed.  In older versions, the search path was relative to the directory where `webinject.pl` was, but in newer versions the search path is the current working directory (i.e. the directory path returned by `pwd`).

As part of a pull-request that was committed and released in v1.9.4, I put in a little extra logic to try and standardise where Webinject looks for a *default* config.xml file.  I felt this extra logic was more in-keeping with the spirit of that in v1.4.1.

Now, the following applies:

1. if you specify `-c config.xml`, it will try to find a file called `config.xml` in the working directory
2. if you specify `-c foo.xml`, it will try to find a file called `foo.xml` in the working directory
3. if you specify `-c /pathto/webinject-1.9.4/config.xml`, it will try to find a file called `config.xml` in the literal path `/pathto/webinject-1.9.4`
4. if you specify `-c /pathto/webinject-1.9.4/foo.xml`, it will try to find a file called `foo.xml` in the literal path `/pathto/webinject-1.9.4`
5. if you do *not* specify `-c ...`, and a file called `config.xml` exists in the working directory, that file is used
6. if you do *not* specify `-c ...`, and a file called `config.xml` exists in the same directory as `webinject.pl`, that file is used (this is extra logic that I added)
7. if you do *not* specify `-c ...`, and a file called `config.xml` does not exist in the same directory as `webinject.pl`, it may also look in the same directory as `Webinject.pm`.

From one of those options, you should be able to formulate a command-line that suits your needs.
