### ISSUE TITLE
use of uninitialized value $val in substitution (s///) at check_webinject line 1582

### ISSUE THREAD

**Issue by crichterhsu** [sni/Webinject#9]
Hi there,

I'm using Webinject for a login and mail sending test on a horde webmailer. There seems to be an error while parsing the response. Googling it has given the same error for other versions (1.41) with the hint to use the actual version. Unfortunately I do (1.86) and still get this error. This is my command line:

root@rzicinga:/usr/lib/nagios/plugins/others/webinject# ./check_webinject -c config.xml webmail.unibw-hamburg.de.xml
Use of uninitialized value $val in substitution (s///) at ./check_webinject line 1582.
WebInject CRITICAL - case #4: Failed Positive Verification, can not find a string matching regex: Betre

Test: webmail.unibw-hamburg.de.xml - 1
Desc: Login in Horde Webmail
POST Request: https://webmail.unibw-hamburg.de/hordegroupware/login.php
Passed HTTP Response Code Verification (not in error range)
TEST CASE PASSED
## Response Time = 0.167 sec

Test: webmail.unibw-hamburg.de.xml - 2
Desc: Wechsel auf die Inbox
GET Request: https://webmail.unibw-hamburg.de/hordegroupware/imp/mailbox.php?mailbox=INBOX
Passed HTTP Response Code Verification (not in error range)
TEST CASE PASSED
## Response Time = 0.101 sec

Test: webmail.unibw-hamburg.de.xml - 3
Desc: Folge der Weiterleitung
GET Request: https://webmail.unibw-hamburg.de/hordegroupware/imp/redirect.php?actionID=login&autologin=1&server_key=imap
Passed HTTP Response Code Verification (not in error range)
TEST CASE PASSED
## Response Time = 0.101 sec

Test: webmail.unibw-hamburg.de.xml - 4
Desc: Enter form send mail
GET Request: https://webmail.unibw-hamburg.de/hordegroupware/imp/compose.php?mailbox=INBOX&uniq=1391607126.7291
Passed HTTP Response Code Verification (not in error range)
Verify: 'Betre'
Failed Positive Verification
Failed Parseresult, cannot find uniq=(_)"
Failed Parseresult, cannot find compose_requestToken" value="(_)"
Failed Parseresult, cannot find compose_formToken" value="(_)"
Failed Parseresult, cannot find messageCache" value="(_)"
TEST CASE FAILED : case #4: Failed Positive Verification, can not find a string matching regex: Betre
## Response Time = 0.101 sec

Test Cases Run: 4
Test Cases Passed: 3
Test Cases Failed: 1
Verifications Passed: 4
Verifications Failed: 1

These are the testcases: 

<testcases repeat="1">

```
<testvar varname="HORDE_USER">someone@hsu-hh.de</testvar>
<testvar varname="HORDE_PASS">supersecretpw</testvar>
<testvar varname="SOURCE_EMAIL">rzicinga@hsu-hh.de</testvar>
<testvar varname="DEST_EMAIL">rzicinga@hsu-hh.de</testvar>
<testvar varname="DEST_FOLDER">Monitoring_nicht_loeschen</testvar>
```

<case
    id="1"
    description1="Login in Horde Webmail"
    method="post"
    url="${BASE_URL}/login.php"
    postbody="url=&horde_user=${HORDE_USER}&horde_pass=${HORDE_PASS}&new_lang=de_DE"
    parseresponse1="Horde=|;"
    parseresponse2="auth_key=|;"
/>

<case
    id="2"
    description1="Wechsel auf die Inbox"
    url="${BASE_URL}/imp/mailbox.php?mailbox=INBOX"
    method="get"
    parseresponse="Location: |\n"
/>

<case
    id="3"
    description1="Folge der Weiterleitung"
    url="{PARSEDRESULT}"
    method="get"
/>

<case
    id="4"
    description1="Enter form send mail"
    url="${BASE_URL}/imp/compose.php?mailbox=INBOX&uniq={TIMESTAMP}"
    method="get"
    parseresponse='uniq=|"|escape'
    parseresponse1='compose_requestToken" value="|"|escape'
    parseresponse2='compose_formToken" value="|"|escape'
    parseresponse3='messageCache" value="|"|escape'
    verifypositive="Betre"
/>

<case
    id="5"
    description1="Send form send mail"
    method="post"
    url="${BASE_URL}/imp/compose.php"
    posttype="multipart/form-data"
    postbody="( uniq=>'{PARSEDRESULT}', MAX_FILE_SIZE=>52428800, actionID=>'send_message', compose_requestToken=>'{PARSEDRESULT1}', compose_formToken=>'{PARSEDRESULT2}', messageCache=>'{PARSEDRESULT3}', mailbox=>'INBOX', thismailbox=>'', page=>'', start=>'', popup=>'', attachmentAction=>'', reloaded=>'1', oldrtemode=>'0', rtemode=>'0', index=>'', last_identity=>'0', identity=>'tag:identity_default', to=>'${DEST_EMAIL}', cc=>'', bcc=>'', subject=>'{TIMESTAMP}', charset=>'ISO-8859-1', message=>'Texttest', filename=>'', upload_disposition_1=>'attachment', save_attachments_select=>'0', link_attachments=>'0' )"
    sleep="7"
        verifypositive="script type"
        verifypositivenext="{TIMESTAMP}"
/>
<case
        id="6"
        description1="Find mail"
        method="get"
        url="${BASE_URL}/imp/mailbox.php?mailbox=INBOX"
/>

Thanks in advance for any help!

**Comment by gitmopp** [comment]
With the version 1.90 the error is
`Use of uninitialized value $val in substitution (s///) at /usr/lib/perl5/vendor_perl/5.18.2/Webinject.pm line 1597.`
The following modification in `Webinject.pm` at line 1597 should fix the problem:
`$val =~ s/[^-\w.,!~'()\/\ ]/uc sprintf "%%%02x", ord $&/egmx if defined $val;`

**Comment by sni** [comment]
Thanks for looking into this. Could you please open a pull request and reference this issue?
